sudo: required

language: python

services:
  - docker

python:
  - "3.6"

branches:
  only:
    - master

script:
  - pip install localstack awscli-local[ver1]
  - docker pull localstack/localstack
  - make start
  - sleep 10
  - sudo sed -i '1inameserver 127.0.0.1' /etc/resolv.conf
  - cat /etc/resolv.conf
  - make test-ci-all

notifications:
  email: false
