service: test-layers

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: testbucket

functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: TestLambdaLayer }
    events:
      - schedule: "cron(0 * * * ? *)"
      - http:
          path: "/"
          method: "get"
          integration: "lambda-proxy"

layers:
  test:
    path: layer

resources:
  Resources:
    ApiGatewayRestApi:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Name: "${self:provider.stage}-${self:service}"
    GatewayResponseDefault400:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "DEFAULT_4XX"
        ResponseTemplates:
          application/json: '{"errors":[{"message":"Custom text."}]}'

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
