service: localstack-websockets

provider:
  name: aws
  deploymentBucket:
    name: localstack-websockets-serverless

package:
  exclude:
    - .venv/**

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

custom:
  localstack:
    stages: [local]

functions:
  connectionHandler:
    handler: handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.handler
    events:
      - websocket:
          route: $default
  actionHandler:
    handler: handler.handler
    events:
      - websocket:
          route: test-action
